name: TBEorNotTBE
favicon: null
layout_spectrum: 0.82315
typography_spectrum: 0.55718
title: That is the Question
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0e4cff'
    - '#ffffff'
    - '#626262'
    - '#a40f11'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
